// Comprehensive commercial airport database
const AIRPORTS_DB = [
  // INDIA
  {name:'Mumbai',code:'BOM',flag:'🇮🇳',country:'India',keywords:['bombay','mumbai','india','gateway']},
  {name:'Delhi',code:'DEL',flag:'🇮🇳',country:'India',keywords:['delhi','new delhi','india','capital']},
  {name:'Bangalore',code:'BLR',flag:'🇮🇳',country:'India',keywords:['bangalore','bengaluru','india','tech']},
  {name:'Chennai',code:'MAA',flag:'🇮🇳',country:'India',keywords:['chennai','madras','india']},
  {name:'Hyderabad',code:'HYD',flag:'🇮🇳',country:'India',keywords:['hyderabad','india']},
  {name:'Kolkata',code:'CCU',flag:'🇮🇳',country:'India',keywords:['kolkata','calcutta','india']},
  {name:'Kochi',code:'COK',flag:'🇮🇳',country:'India',keywords:['kochi','cochin','india','kerala']},
  {name:'Thiruvananthapuram',code:'TRV',flag:'🇮🇳',country:'India',keywords:['trivandrum','kerala']},
  {name:'Ahmedabad',code:'AMD',flag:'🇮🇳',country:'India',keywords:['ahmedabad','gujarat']},
  {name:'Pune',code:'PNQ',flag:'🇮🇳',country:'India',keywords:['pune','maharashtra']},
  {name:'Goa',code:'GOI',flag:'🇮🇳',country:'India',keywords:['goa','beach']},
  {name:'Jaipur',code:'JAI',flag:'🇮🇳',country:'India',keywords:['jaipur','rajasthan','pink city']},
  {name:'Lucknow',code:'LKO',flag:'🇮🇳',country:'India',keywords:['lucknow','nawab']},
  {name:'Amritsar',code:'ATQ',flag:'🇮🇳',country:'India',keywords:['amritsar','golden temple']},
  {name:'Srinagar',code:'SXR',flag:'🇮🇳',country:'India',keywords:['srinagar','kashmir']},
  {name:'Varanasi',code:'VNS',flag:'🇮🇳',country:'India',keywords:['varanasi','banaras']},
  {name:'Indore',code:'IDR',flag:'🇮🇳',country:'India',keywords:['indore']},
  {name:'Nagpur',code:'NAG',flag:'🇮🇳',country:'India',keywords:['nagpur','orange city']},
  {name:'Patna',code:'PAT',flag:'🇮🇳',country:'India',keywords:['patna','bihar']},
  {name:'Bhopal',code:'BHO',flag:'🇮🇳',country:'India',keywords:['bhopal']},
  {name:'Chandigarh',code:'IXC',flag:'🇮🇳',country:'India',keywords:['chandigarh']},
  {name:'Coimbatore',code:'CJB',flag:'🇮🇳',country:'India',keywords:['coimbatore']},
  {name:'Mangalore',code:'IXE',flag:'🇮🇳',country:'India',keywords:['mangalore','mangaluru']},
  {name:'Visakhapatnam',code:'VTZ',flag:'🇮🇳',country:'India',keywords:['vizag','visakhapatnam']},
  {name:'Guwahati',code:'GAU',flag:'🇮🇳',country:'India',keywords:['guwahati','assam']},
  {name:'Dehradun',code:'DED',flag:'🇮🇳',country:'India',keywords:['dehradun','uttarakhand']},
  {name:'Ranchi',code:'IXR',flag:'🇮🇳',country:'India',keywords:['ranchi','jharkhand']},
  {name:'Raipur',code:'RPR',flag:'🇮🇳',country:'India',keywords:['raipur','chhattisgarh']},
  {name:'Madurai',code:'IXM',flag:'🇮🇳',country:'India',keywords:['madurai','tamil nadu']},
  {name:'Tiruchirappalli',code:'TRZ',flag:'🇮🇳',country:'India',keywords:['trichy']},
  {name:'Bagdogra',code:'IXB',flag:'🇮🇳',country:'India',keywords:['bagdogra','siliguri','darjeeling']},
  {name:'Udaipur',code:'UDR',flag:'🇮🇳',country:'India',keywords:['udaipur','rajasthan']},
  {name:'Jodhpur',code:'JDH',flag:'🇮🇳',country:'India',keywords:['jodhpur','blue city']},
  {name:'Imphal',code:'IMF',flag:'🇮🇳',country:'India',keywords:['imphal','manipur']},
  {name:'Agartala',code:'IXA',flag:'🇮🇳',country:'India',keywords:['agartala','tripura']},
  {name:'Dibrugarh',code:'DIB',flag:'🇮🇳',country:'India',keywords:['dibrugarh','assam']},
  {name:'Port Blair',code:'IXZ',flag:'🇮🇳',country:'India',keywords:['port blair','andaman']},
  {name:'Leh',code:'IXL',flag:'🇮🇳',country:'India',keywords:['leh','ladakh']},
  // PAKISTAN
  {name:'Lahore',code:'LHE',flag:'🇵🇰',country:'Pakistan',keywords:['lahore','punjab']},
  {name:'Karachi',code:'KHI',flag:'🇵🇰',country:'Pakistan',keywords:['karachi','sindh']},
  {name:'Islamabad',code:'ISB',flag:'🇵🇰',country:'Pakistan',keywords:['islamabad','capital']},
  {name:'Peshawar',code:'PEW',flag:'🇵🇰',country:'Pakistan',keywords:['peshawar']},
  {name:'Quetta',code:'UET',flag:'🇵🇰',country:'Pakistan',keywords:['quetta']},
  {name:'Faisalabad',code:'LYP',flag:'🇵🇰',country:'Pakistan',keywords:['faisalabad']},
  {name:'Multan',code:'MUX',flag:'🇵🇰',country:'Pakistan',keywords:['multan']},
  // MIDDLE EAST
  {name:'Dubai',code:'DXB',flag:'🇦🇪',country:'UAE',keywords:['dubai','uae','emirates','luxury','burj']},
  {name:'Abu Dhabi',code:'AUH',flag:'🇦🇪',country:'UAE',keywords:['abu dhabi','uae']},
  {name:'Sharjah',code:'SHJ',flag:'🇦🇪',country:'UAE',keywords:['sharjah','uae']},
  {name:'Doha',code:'DOH',flag:'🇶🇦',country:'Qatar',keywords:['doha','qatar']},
  {name:'Riyadh',code:'RUH',flag:'🇸🇦',country:'Saudi Arabia',keywords:['riyadh','saudi']},
  {name:'Jeddah',code:'JED',flag:'🇸🇦',country:'Saudi Arabia',keywords:['jeddah','hajj','umrah']},
  {name:'Medina',code:'MED',flag:'🇸🇦',country:'Saudi Arabia',keywords:['medina','madinah']},
  {name:'Dammam',code:'DMM',flag:'🇸🇦',country:'Saudi Arabia',keywords:['dammam']},
  {name:'Muscat',code:'MCT',flag:'🇴🇲',country:'Oman',keywords:['muscat','oman']},
  {name:'Kuwait City',code:'KWI',flag:'🇰🇼',country:'Kuwait',keywords:['kuwait']},
  {name:'Bahrain',code:'BAH',flag:'🇧🇭',country:'Bahrain',keywords:['bahrain']},
  {name:'Amman',code:'AMM',flag:'🇯🇴',country:'Jordan',keywords:['amman','jordan']},
  {name:'Beirut',code:'BEY',flag:'🇱🇧',country:'Lebanon',keywords:['beirut','lebanon']},
  {name:'Baghdad',code:'BGW',flag:'🇮🇶',country:'Iraq',keywords:['baghdad','iraq']},
  {name:'Erbil',code:'EBL',flag:'🇮🇶',country:'Iraq',keywords:['erbil','kurdistan']},
  {name:'Tehran',code:'IKA',flag:'🇮🇷',country:'Iran',keywords:['tehran','iran']},
  {name:'Tel Aviv',code:'TLV',flag:'🇮🇱',country:'Israel',keywords:['tel aviv','israel']},
  // SOUTHEAST ASIA
  {name:'Singapore',code:'SIN',flag:'🇸🇬',country:'Singapore',keywords:['singapore','changi','marina']},
  {name:'Bangkok',code:'BKK',flag:'🇹🇭',country:'Thailand',keywords:['bangkok','thailand']},
  {name:'Phuket',code:'HKT',flag:'🇹🇭',country:'Thailand',keywords:['phuket','beach']},
  {name:'Chiang Mai',code:'CNX',flag:'🇹🇭',country:'Thailand',keywords:['chiang mai']},
  {name:'Kuala Lumpur',code:'KUL',flag:'🇲🇾',country:'Malaysia',keywords:['kuala lumpur','kl','petronas']},
  {name:'Penang',code:'PEN',flag:'🇲🇾',country:'Malaysia',keywords:['penang']},
  {name:'Jakarta',code:'CGK',flag:'🇮🇩',country:'Indonesia',keywords:['jakarta']},
  {name:'Bali',code:'DPS',flag:'🇮🇩',country:'Indonesia',keywords:['bali','denpasar','beach']},
  {name:'Surabaya',code:'SUB',flag:'🇮🇩',country:'Indonesia',keywords:['surabaya']},
  {name:'Manila',code:'MNL',flag:'🇵🇭',country:'Philippines',keywords:['manila']},
  {name:'Cebu',code:'CEB',flag:'🇵🇭',country:'Philippines',keywords:['cebu']},
  {name:'Ho Chi Minh City',code:'SGN',flag:'🇻🇳',country:'Vietnam',keywords:['ho chi minh','saigon']},
  {name:'Hanoi',code:'HAN',flag:'🇻🇳',country:'Vietnam',keywords:['hanoi']},
  {name:'Phnom Penh',code:'PNH',flag:'🇰🇭',country:'Cambodia',keywords:['phnom penh']},
  {name:'Siem Reap',code:'REP',flag:'🇰🇭',country:'Cambodia',keywords:['siem reap','angkor']},
  {name:'Yangon',code:'RGN',flag:'🇲🇲',country:'Myanmar',keywords:['yangon','rangoon']},
  // EAST ASIA
  {name:'Hong Kong',code:'HKG',flag:'🇭🇰',country:'Hong Kong',keywords:['hong kong']},
  {name:'Tokyo Narita',code:'NRT',flag:'🇯🇵',country:'Japan',keywords:['tokyo','narita']},
  {name:'Tokyo Haneda',code:'HND',flag:'🇯🇵',country:'Japan',keywords:['tokyo','haneda']},
  {name:'Osaka',code:'KIX',flag:'🇯🇵',country:'Japan',keywords:['osaka','kansai']},
  {name:'Seoul Incheon',code:'ICN',flag:'🇰🇷',country:'South Korea',keywords:['seoul','incheon','kpop']},
  {name:'Busan',code:'PUS',flag:'🇰🇷',country:'South Korea',keywords:['busan']},
  {name:'Beijing',code:'PEK',flag:'🇨🇳',country:'China',keywords:['beijing','great wall']},
  {name:'Shanghai Pudong',code:'PVG',flag:'🇨🇳',country:'China',keywords:['shanghai','pudong']},
  {name:'Guangzhou',code:'CAN',flag:'🇨🇳',country:'China',keywords:['guangzhou','canton']},
  {name:'Shenzhen',code:'SZX',flag:'🇨🇳',country:'China',keywords:['shenzhen']},
  {name:'Chengdu',code:'CTU',flag:'🇨🇳',country:'China',keywords:['chengdu','panda']},
  {name:'Taipei',code:'TPE',flag:'🇹🇼',country:'Taiwan',keywords:['taipei','taiwan']},
  {name:'Macau',code:'MFM',flag:'🇲🇴',country:'Macau',keywords:['macau','macao']},
  // SOUTH ASIA
  {name:'Colombo',code:'CMB',flag:'🇱🇰',country:'Sri Lanka',keywords:['colombo','sri lanka']},
  {name:'Kathmandu',code:'KTM',flag:'🇳🇵',country:'Nepal',keywords:['kathmandu','himalaya']},
  {name:'Dhaka',code:'DAC',flag:'🇧🇩',country:'Bangladesh',keywords:['dhaka']},
  {name:'Maldives',code:'MLE',flag:'🇲🇻',country:'Maldives',keywords:['maldives','male','honeymoon','paradise']},
  {name:'Thimphu',code:'PBH',flag:'🇧🇹',country:'Bhutan',keywords:['thimphu','paro','bhutan']},
  // EUROPE
  {name:'London Heathrow',code:'LHR',flag:'🇬🇧',country:'UK',keywords:['london','heathrow','england']},
  {name:'London Gatwick',code:'LGW',flag:'🇬🇧',country:'UK',keywords:['london','gatwick']},
  {name:'Manchester',code:'MAN',flag:'🇬🇧',country:'UK',keywords:['manchester']},
  {name:'Edinburgh',code:'EDI',flag:'🇬🇧',country:'UK',keywords:['edinburgh','scotland']},
  {name:'Birmingham',code:'BHX',flag:'🇬🇧',country:'UK',keywords:['birmingham']},
  {name:'Paris CDG',code:'CDG',flag:'🇫🇷',country:'France',keywords:['paris','charles de gaulle']},
  {name:'Paris Orly',code:'ORY',flag:'🇫🇷',country:'France',keywords:['paris','orly']},
  {name:'Nice',code:'NCE',flag:'🇫🇷',country:'France',keywords:['nice','riviera']},
  {name:'Lyon',code:'LYS',flag:'🇫🇷',country:'France',keywords:['lyon']},
  {name:'Frankfurt',code:'FRA',flag:'🇩🇪',country:'Germany',keywords:['frankfurt']},
  {name:'Munich',code:'MUC',flag:'🇩🇪',country:'Germany',keywords:['munich','bavaria']},
  {name:'Berlin',code:'BER',flag:'🇩🇪',country:'Germany',keywords:['berlin']},
  {name:'Dusseldorf',code:'DUS',flag:'🇩🇪',country:'Germany',keywords:['dusseldorf']},
  {name:'Hamburg',code:'HAM',flag:'🇩🇪',country:'Germany',keywords:['hamburg']},
  {name:'Amsterdam',code:'AMS',flag:'🇳🇱',country:'Netherlands',keywords:['amsterdam','schiphol']},
  {name:'Rome Fiumicino',code:'FCO',flag:'🇮🇹',country:'Italy',keywords:['rome','fiumicino']},
  {name:'Milan Malpensa',code:'MXP',flag:'🇮🇹',country:'Italy',keywords:['milan','malpensa']},
  {name:'Venice',code:'VCE',flag:'🇮🇹',country:'Italy',keywords:['venice']},
  {name:'Naples',code:'NAP',flag:'🇮🇹',country:'Italy',keywords:['naples','napoli']},
  {name:'Madrid',code:'MAD',flag:'🇪🇸',country:'Spain',keywords:['madrid']},
  {name:'Barcelona',code:'BCN',flag:'🇪🇸',country:'Spain',keywords:['barcelona','gaudi']},
  {name:'Malaga',code:'AGP',flag:'🇪🇸',country:'Spain',keywords:['malaga','costa del sol']},
  {name:'Lisbon',code:'LIS',flag:'🇵🇹',country:'Portugal',keywords:['lisbon']},
  {name:'Porto',code:'OPO',flag:'🇵🇹',country:'Portugal',keywords:['porto']},
  {name:'Zurich',code:'ZRH',flag:'🇨🇭',country:'Switzerland',keywords:['zurich','alps']},
  {name:'Geneva',code:'GVA',flag:'🇨🇭',country:'Switzerland',keywords:['geneva']},
  {name:'Vienna',code:'VIE',flag:'🇦🇹',country:'Austria',keywords:['vienna','wien']},
  {name:'Brussels',code:'BRU',flag:'🇧🇪',country:'Belgium',keywords:['brussels']},
  {name:'Dublin',code:'DUB',flag:'🇮🇪',country:'Ireland',keywords:['dublin']},
  {name:'Copenhagen',code:'CPH',flag:'🇩🇰',country:'Denmark',keywords:['copenhagen']},
  {name:'Stockholm',code:'ARN',flag:'🇸🇪',country:'Sweden',keywords:['stockholm','arlanda']},
  {name:'Oslo',code:'OSL',flag:'🇳🇴',country:'Norway',keywords:['oslo']},
  {name:'Helsinki',code:'HEL',flag:'🇫🇮',country:'Finland',keywords:['helsinki']},
  {name:'Warsaw',code:'WAW',flag:'🇵🇱',country:'Poland',keywords:['warsaw']},
  {name:'Prague',code:'PRG',flag:'🇨🇿',country:'Czechia',keywords:['prague']},
  {name:'Budapest',code:'BUD',flag:'🇭🇺',country:'Hungary',keywords:['budapest']},
  {name:'Bucharest',code:'OTP',flag:'🇷🇴',country:'Romania',keywords:['bucharest']},
  {name:'Athens',code:'ATH',flag:'🇬🇷',country:'Greece',keywords:['athens','acropolis']},
  {name:'Santorini',code:'JTR',flag:'🇬🇷',country:'Greece',keywords:['santorini','romantic']},
  {name:'Istanbul',code:'IST',flag:'🇹🇷',country:'Turkey',keywords:['istanbul']},
  {name:'Antalya',code:'AYT',flag:'🇹🇷',country:'Turkey',keywords:['antalya']},
  {name:'Moscow',code:'SVO',flag:'🇷🇺',country:'Russia',keywords:['moscow','sheremetyevo']},
  {name:'St Petersburg',code:'LED',flag:'🇷🇺',country:'Russia',keywords:['st petersburg']},
  {name:'Reykjavik',code:'KEF',flag:'🇮🇸',country:'Iceland',keywords:['reykjavik','iceland']},
  // NORTH AMERICA
  {name:'New York JFK',code:'JFK',flag:'🇺🇸',country:'USA',keywords:['new york','jfk','nyc','manhattan']},
  {name:'New York Newark',code:'EWR',flag:'🇺🇸',country:'USA',keywords:['newark','new york']},
  {name:'Los Angeles',code:'LAX',flag:'🇺🇸',country:'USA',keywords:['los angeles','la','hollywood']},
  {name:'Chicago',code:'ORD',flag:'🇺🇸',country:'USA',keywords:['chicago','ohare']},
  {name:'San Francisco',code:'SFO',flag:'🇺🇸',country:'USA',keywords:['san francisco','silicon']},
  {name:'Miami',code:'MIA',flag:'🇺🇸',country:'USA',keywords:['miami','florida','beach']},
  {name:'Dallas',code:'DFW',flag:'🇺🇸',country:'USA',keywords:['dallas','fort worth','texas']},
  {name:'Houston',code:'IAH',flag:'🇺🇸',country:'USA',keywords:['houston','texas']},
  {name:'Atlanta',code:'ATL',flag:'🇺🇸',country:'USA',keywords:['atlanta','georgia']},
  {name:'Washington DC',code:'IAD',flag:'🇺🇸',country:'USA',keywords:['washington','dulles','dc']},
  {name:'Boston',code:'BOS',flag:'🇺🇸',country:'USA',keywords:['boston']},
  {name:'Seattle',code:'SEA',flag:'🇺🇸',country:'USA',keywords:['seattle']},
  {name:'Denver',code:'DEN',flag:'🇺🇸',country:'USA',keywords:['denver','colorado']},
  {name:'Las Vegas',code:'LAS',flag:'🇺🇸',country:'USA',keywords:['las vegas','vegas']},
  {name:'Orlando',code:'MCO',flag:'🇺🇸',country:'USA',keywords:['orlando','disney','florida']},
  {name:'Honolulu',code:'HNL',flag:'🇺🇸',country:'USA',keywords:['honolulu','hawaii']},
  {name:'Toronto',code:'YYZ',flag:'🇨🇦',country:'Canada',keywords:['toronto','pearson']},
  {name:'Vancouver',code:'YVR',flag:'🇨🇦',country:'Canada',keywords:['vancouver']},
  {name:'Montreal',code:'YUL',flag:'🇨🇦',country:'Canada',keywords:['montreal']},
  {name:'Calgary',code:'YYC',flag:'🇨🇦',country:'Canada',keywords:['calgary']},
  {name:'Mexico City',code:'MEX',flag:'🇲🇽',country:'Mexico',keywords:['mexico city']},
  {name:'Cancun',code:'CUN',flag:'🇲🇽',country:'Mexico',keywords:['cancun','beach','resort']},
  // SOUTH AMERICA
  {name:'Sao Paulo',code:'GRU',flag:'🇧🇷',country:'Brazil',keywords:['sao paulo']},
  {name:'Rio de Janeiro',code:'GIG',flag:'🇧🇷',country:'Brazil',keywords:['rio','rio de janeiro']},
  {name:'Buenos Aires',code:'EZE',flag:'🇦🇷',country:'Argentina',keywords:['buenos aires']},
  {name:'Santiago',code:'SCL',flag:'🇨🇱',country:'Chile',keywords:['santiago','chile']},
  {name:'Lima',code:'LIM',flag:'🇵🇪',country:'Peru',keywords:['lima','peru']},
  {name:'Bogota',code:'BOG',flag:'🇨🇴',country:'Colombia',keywords:['bogota','colombia']},
  // AFRICA
  {name:'Cairo',code:'CAI',flag:'🇪🇬',country:'Egypt',keywords:['cairo','pyramids']},
  {name:'Johannesburg',code:'JNB',flag:'🇿🇦',country:'South Africa',keywords:['johannesburg']},
  {name:'Cape Town',code:'CPT',flag:'🇿🇦',country:'South Africa',keywords:['cape town']},
  {name:'Nairobi',code:'NBO',flag:'🇰🇪',country:'Kenya',keywords:['nairobi','safari']},
  {name:'Lagos',code:'LOS',flag:'🇳🇬',country:'Nigeria',keywords:['lagos']},
  {name:'Addis Ababa',code:'ADD',flag:'🇪🇹',country:'Ethiopia',keywords:['addis ababa']},
  {name:'Casablanca',code:'CMN',flag:'🇲🇦',country:'Morocco',keywords:['casablanca']},
  {name:'Marrakech',code:'RAK',flag:'🇲🇦',country:'Morocco',keywords:['marrakech']},
  {name:'Algiers',code:'ALG',flag:'🇩🇿',country:'Algeria',keywords:['algiers']},
  {name:'Tunis',code:'TUN',flag:'🇹🇳',country:'Tunisia',keywords:['tunis']},
  {name:'Dar es Salaam',code:'DAR',flag:'🇹🇿',country:'Tanzania',keywords:['dar es salaam']},
  {name:'Accra',code:'ACC',flag:'🇬🇭',country:'Ghana',keywords:['accra']},
  {name:'Mauritius',code:'MRU',flag:'🇲🇺',country:'Mauritius',keywords:['mauritius']},
  // OCEANIA
  {name:'Sydney',code:'SYD',flag:'🇦🇺',country:'Australia',keywords:['sydney','opera']},
  {name:'Melbourne',code:'MEL',flag:'🇦🇺',country:'Australia',keywords:['melbourne']},
  {name:'Brisbane',code:'BNE',flag:'🇦🇺',country:'Australia',keywords:['brisbane']},
  {name:'Perth',code:'PER',flag:'🇦🇺',country:'Australia',keywords:['perth']},
  {name:'Auckland',code:'AKL',flag:'🇳🇿',country:'New Zealand',keywords:['auckland']},
  {name:'Christchurch',code:'CHC',flag:'🇳🇿',country:'New Zealand',keywords:['christchurch']},
  {name:'Fiji',code:'NAN',flag:'🇫🇯',country:'Fiji',keywords:['fiji','nadi']},
  // CENTRAL ASIA
  {name:'Tashkent',code:'TAS',flag:'🇺🇿',country:'Uzbekistan',keywords:['tashkent']},
  {name:'Almaty',code:'ALA',flag:'🇰🇿',country:'Kazakhstan',keywords:['almaty']},
  {name:'Tbilisi',code:'TBS',flag:'🇬🇪',country:'Georgia',keywords:['tbilisi']},
  {name:'Baku',code:'GYD',flag:'🇦🇿',country:'Azerbaijan',keywords:['baku']},
];
